### ISSUE TITLE
BigBank - SystemContext - Relations

### ISSUE THREAD

**Issue by brunopenso** [structurizr/dsl#111]
Hi Team,

Here we are trying to understand if the **structurizr**  is generating the diagram in the correct way comparing to the c4model definition that you can find it here > https://c4model.com/#SystemContextDiagram

Reading the c4 definition, we understood that the system in focus will be placed in the middle of the diagram, blue coior, and all **direct** relations will be drawn on the diagram resulting to this:

<img width="747" alt="image" src="https://user-images.githubusercontent.com/1093677/153921671-c90623d4-c37a-456e-a739-e3b069c9148d.png">

Now let's suppose that the mainframe and the email system talk to each other, I added this line `mainframe -> email "sends mail "IMAP"` to the BigBank sample at line 53, and the result is:

<img width="434" alt="image" src="https://user-images.githubusercontent.com/1093677/153921876-c8658a36-6048-4eb4-a95b-b4218d9cdad6.png">

As you can see there is a connection between mainframe and email system showing on the systemcontext of **Internet Banking Systems** 

Looking to the C4model definition it looks like this is an incorrect behaviour because the connection between mainframe and email are not related to the internet banking system.

Is this a bug? Or we are misunderstanding the c4 definition?

**Comment by simonbrowndotje** [comment]
The second diagram is showing more relationships than is necessary, but it's still a System Context diagram, because it's showing the software system in scope, and the people + software systems around it.

**Comment by brunopenso** [comment]
Perfect @simonbrowndotje 

I consider this a BUG because that connection between mainframe and email isn't part of the context of `Internet Banking`.

I will take a look at the source code and see if I can fix it.

**Comment by simonbrowndotje** [comment]
I can point you to the code that implements `include *`, but this isn't a bug. There are times when it's important to show relationships where the software system in scope isn't the source or destination. You can see an example of this above - the system context diagram for the Internet Banking System includes the relationship between the E-mail System and the Personal Banking Customer. That's useful to include here, because it helps tell a story.

If you need to remove any relationships that `include *` adds by default, you can use the DSL `exclude` statement to exclude them.
