### ISSUE TITLE
Allow !include to use urls that require authentication

### ISSUE THREAD

**Issue by kristofdepypere** [structurizr/dsl#134]
We are using structurizr in our company and we have to make sure all workspaces are private as we don't want to expose anything to the public internet.

We have a parent workspace for modelling the system landscape and child workspaces that hook into the parent to have a nice hierarchical structure that is easy to navigate. We are standardizing completely on the dsl. However we come into the situation we are copy pasting many systems across different workspaces. We would like to have consistency in styling and reuse part of the models between the workspaces but at this point we end up copy pasting. 

What would help us tremendously is to be able to reuse dsl fragments across workspaces. We tried using the !include with https urls however this only accepts public urls without authentication.
Is there any solution that could help us solving our use case ? What if all structurizr dsls are published automatically in the private workspaces and we could reference these from other private workspaces ? Or just allow to add some kind of credentials like an api key in order to access dsl files that are protected on another server.

**Comment by simonbrowndotje** [comment]
> Is there any solution that could help us solving our use case ? What if all structurizr dsls are published automatically in the private workspaces and we could reference these from other private workspaces ? 

If you're using the DSL, you could write a DSL plugin that retrieves your shared workspace (via the web API), and copies the shared elements/relationships/styles across to the "current" workspace. But I wouldn't recommend this approach.

Instead I would:

1. Treat the Structurizr cloud service/on-premises installation as a way to publish a workspace, and place all of your DSL files in source code control.
2. I'd create a build script that gets your shared DSL file from source cod control, and places it on local disk ... removing the need for any URL authentication.
3. You can then use the [workspace extension feature](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#workspace) to extend that shared workspace.

Example:
 - [model.dsl](https://github.com/structurizr/examples/blob/main/dsl/big-bank-plc/model.dsl) defines the system landscape.
 - [internet-banking-system/workspace.dsl](https://github.com/structurizr/examples/blob/main/dsl/big-bank-plc/internet-banking-system/workspace.dsl) extends this to add details for a specific system (via the `!ref` keyword)

**Comment by kristofdepypere** [comment]
Thx for the reply, we'll try out your suggested approach.

**Comment by davidfrtala** [comment]
I would like to reopen this issue as it's still relevant.

We want to achieve that every repository is a workspace, that is describing its software system. Within the current workspace, we want to `!include` all its system dependencies from other repositories/workspaces that are required, thus creating a project scoped diagram.
By this, we would like to achieve that project contributors are also owners of this project workspace diagram, so they will make sure its up to date within their scope of work.

Then, we have a central docs repo, which will be an overall agregator of all workspaces, which will describe our whole company wide architecture.

And this is currently not possible because `.dsl` files are in private repositories so we cannot access them via permalink.
Creating a plugin/script is not very efficient because we would have to manually merge diagrams element by element.

**Comment by simonbrowndotje** [comment]
As I said above, there are a number of ways to deal with this without adding complicated authentication logic to the DSL parser. For example:

### Download all files before parsing

Write a script/program to download authenticated files to a local folder, then run the DSL parser with the `!include` statement referring to those local files. If you did this in Java, you could also add a depedency to the DSL parser and use it directly rather than going via the Structurizr CLI (which is just a Java app itself).

```
public static void main(String[] args) {
  downloadProtectedFiles();
  StructurizrDslParser parser = new StructurizrDslParser();
  parser.parse(new File("workspace.dsl"));
  Workspace workspace = parser.getWorkspace();
}
```

### Download specific files during DSL processing

Write yourself a script/plugin to download a protected resource, then `!include` it. For example:

```
workspace {
  model {
    ...
    !plugin DownloadProtectedFilePlugin https://company.github.com/repo/file.dsl
    !include file.dsl
  }
}
```

The DSL parser is fully open source, so you can fork to add authentication to `!include` if desired. It's not a feature that I want to support though.
