### ISSUE TITLE
Multi-line Strings

### ISSUE THREAD

**Issue by erwanosouf** [structurizr/dsl#137]
Is there a way to have multiline strings in the DSL ?

This would allow for easier readability of long fields such as descriptions or perspectives.
Also what is the proper way to introduce line breaks for rendering in such fields ?

I saw that \n seems to work, but using line breaks for the source DSL file would be great !

**Comment by simonbrowndotje** [comment]
The DSL parser is designed to work with line breaks, so multi-line strings are not supported I'm afraid.

**Comment by aidmax** [comment]
Also, struggling with readability looking at long description lines :(

**Comment by Kaligule** [comment]
One way to make this possible without breaking the current syntax would be to allow for multiple description lines.
Then, instead of using the value of the last  value, concatinate them with separating \n.

Example

```
description "aaa"
description "bbb"
description "ccc"
```

This currently results in the description "ccc", but could be changed to result in "aaa**\n**bbb**\n**ccc"
