### ISSUE TITLE
Allow the "default" color

### ISSUE THREAD

**Issue by dgutson** [structurizr/dsl#201]
Situation: I want to specify the color for most of the groups, but leave the default for few groups.
So, I'd like to say
```
    element "Group" {
        color "green"
    }
    element "Group:onegrp" {
        color "default"
    }
```

**Comment by simonbrowndotje** [comment]
This isn't something I want to add to the underlying Java library, because it also requires changing how all of the diagram renderers/exporters work. I'd suggest just creating a string constant; for example:

```
!constant "DEFAULT_GROUP_COLOR" "#cccccc"

...

styles {
    element "Group" {
        color "green"
    }
    element "Group:onegrp" {
        color "${DEFAULT_GROUP_COLOR}"
    }
}
```

Alternatively, if you're using one of the exporters, you can fork it to add your own group style handling code; for example -> https://github.com/structurizr/export/blob/main/src/main/java/com/structurizr/export/plantuml/StructurizrPlantUMLExporter.java#L129

**Comment by dgutson** [comment]
Maybe this could be a good opportunity to create the "constants.dsl" standards include file? (I didn't know it was `#cccccc`). Maybe worth to move there other constants/defaults as well, not only as a matter to get rid of magic numbers, but also for documentation, for use cases as the original post, and for overrides.
