### ISSUE TITLE
Support for specifying element coordinates and relationship control points?

### ISSUE THREAD

**Issue by aviflax** [structurizr/dsl#4]
Hi Simon, I’m just now trying out the DSL for a real project, and so far I’m very impressed!

One question: I don’t see a way to specify element coordinates and/or relationship control points, when *not* using auto-layout. Am I missing something, or is this just not yet supported? If the latter, do you intend to add such support at some point?

Thanks!
Avi

**Comment by simonbrowndotje** [comment]
Thanks! Since there's no transformation process to convert a workspace back to the DSL (Express was 2-way, the DSL is 1-way only), layout information is stored in the workspace (in the JSON) format, rather than the DSL itself.

**Comment by aviflax** [comment]
OK, so is there a workflow for manually positioning elements in a view that is defined and maintained via the DSL? By which I mean, the DSL file is my main source of truth, and I expect to be regularly pushing it to the workspace. Sorry if this is documented somewhere, maybe I just missed it.

**Comment by simonbrowndotje** [comment]
I would treat the combination of the DSL and the JSON version of the workspace (which you can pull via the CLI) as the combined source of truth. If you wanted to modify the layout position prior to pushing the workspace (and I'm not sure I'd recommend that as an approach, because you're going to lack any visual feedback), you'd need to write a Java program to:

1. Parse the DSL into a workspace (using [StructurizrDslParser.parse(String)](https://github.com/structurizr/dsl/blob/master/src/main/java/com/structurizr/dsl/StructurizrDslParser.java#L147))
2. Set the x,y positions on the elements for each view -> https://github.com/structurizr/java/blob/master/structurizr-core/src/com/structurizr/view/ElementView.java#L58

**Comment by aviflax** [comment]
Thanks Simon. Just to confirm… this is giving me the impression that right now you have in mind for people to use the DSL with auto layout. Is that right?

**Comment by simonbrowndotje** [comment]
No, I actually use the DSL without auto-layout myself. The CLI is based upon the Java client library, so it will attempt to preserve layout information when uploading a new version of the workspace.

**Comment by simonbrowndotje** [comment]
As an example:

1. Go here -> https://structurizr.com/dsl
2. Remove the reference to `autolayout`
3. Click `Refresh`
4. Move the elements around.
5. Click `Refresh` again ... and you should see that the element positions are preserved.

I would say that layout preservation doesn't work when diagram keys are changed, or elements are renamed. This is certainly inconvenient, but the other option is automatic layout, which has its own trade-offs.

**Comment by aviflax** [comment]
That makes sense — thanks Simon! I really appreciate the help!
