### ISSUE TITLE
Allow to edit files other than workspace.dsl

### ISSUE THREAD

**Issue by souliane** [structurizr/dsl#96]
Hi,

it seems like the DSL editor can only edit `workspace.dsl`, but I like to split my model and use `!include` to include other files, that could be stored in the same or a sub-directory.

Is there a way to see/edit those files in the DSL editor?

Thx,
Adrien

**Comment by simonbrowndotje** [comment]
If you're referring to the browser-based DSL editor (available via the Structurizr cloud service/on-premises installation) ... they don't work off the file system, so can only edit whatever is provided in the textbox. See https://structurizr.com/help/dsl for details of the features that are unavailable via the DSL editor.

**Comment by souliane** [comment]
I think I got it, but regardless where the `workspace.dsl` comes from (local filesystem with the lite version, some other source otherwise), I think it should be possible to split your model and leverage `!include`, also when working in the DSL editor.

I understand if this doesn't end up in the lite version, and it doesn't necessarily need to be integrated in the UI, but we could for example pass the file path in the URL params (a bit like https://structurizr.com/dsl?example=big-bank-plc).

This makes me wonder if structurizr cli `push` command pushes all the included files or only the main `*.dsl`... I guess it's not relevant if you do "as code", but it is if you do "as text", isn't it?

**Comment by simonbrowndotje** [comment]
> I think I got it, but regardless where the workspace.dsl comes from (local filesystem with the lite version, some other source otherwise), I think it should be possible to split your model and leverage !include, also when working in the DSL editor.

Structurizr Lite runs locally, on your own computer, and has full access to your file system. For this reason, you can use `!include` and reference other files on your file system. If you would like to leverage `!include` fully, you need to use Structurizr Lite, or the Structurizr CLI.

> I understand if this doesn't end up in the lite version, and it doesn't necessarily need to be integrated in the UI, but we could for example pass the file path in the URL params (a bit like https://structurizr.com/dsl?example=big-bank-plc).

The DSL editor in the cloud service/on-premises installation is running in a web browser, and doesn't have access to your file system by default (for sandboxing/security reasons), so the `!include` feature is restricted to only supporting publicly accessible HTTPS URLs. Scripting support is similar ... it's available in Lite, but disabled in the online editor, because running untrusted code on our servers would be a very bad idea.

Since Structurizr Lite is already available for free, and supports all of the DSL features, there seems very little benefit in providing the ability for the online DSL editor (which only provides basic syntax highlighting anyway) to sync with a local file system, particularly as many users are already hesitant using a cloud-based service for their (often confidential) architecture diagrams/documentation.

> This makes me wonder if structurizr cli push command pushes all the included files or only the main *.dsl... I guess it's not relevant if you do "as code", but it is if you do "as text", isn't it?

The DSL parser built into the Structurizr CLI will parse the DSL file, along with any included files. In essence, it works in the same way Structurizr Lite does, and supports all DSL features. In summary, if you want to use all of the DSL features, you need to use Structurizr Lite or the CLI, perhaps in conjunction with the [C4-Grammar VS Code extension](https://gitlab.com/systemticks/c4-grammar) to provide syntax highlighting, etc.

**Comment by souliane** [comment]
Thanks for the explanation!
